---
"":
- middleware.compress
- middleware.contextualizer
- middleware.static
- middleware.logger
- middleware.logwriter
- middleware.query
- middleware.bodyParser
- middleware.cookieParser
- middleware.session
- middleware.csrf
- middleware.router
- middleware.errorHandler
/:
  get:
  - middleware.redirect
  - middleware.dispatcher
/register:
  post:
  - middleware.validator
  - middleware.auth.register
  get:
  - middleware.dispatcher
/login:
  post:
  - middleware.validator
  - middleware.auth.login
/logout:
  all:
  - middleware.auth.logout
/about:
  get:
  - middleware.dispatcher
/home:
  get:
  - middleware.auth.login
  - middleware.dispatcher
/units/create:
  get:
  - middleware.auth.login
  - middleware.units.create
...
