---
'':
- middleware.compress
- middleware.contextualizer
- middleware.static
- middleware.logger
- middleware.logwriter
- middleware.query
- middleware.bodyParser
- middleware.cookieParser
- middleware.session
- middleware.csrf
- middleware.router
- middleware.errorHandler
/:
  get:
  - middleware.redirect
  - middleware.dispatcher
/register:
  post:
  - middleware.validator
  - middleware.user.register
  get:
  - middleware.dispatcher
/login:
  post:
  - middleware.validator
  - middleware.user.login
/logout:
  all:
  - middleware.user.logout
/about:
  get:
  - middleware.dispatcher
/home:
  get:
  - middleware.user.login
  - middleware.dispatcher
/units:
  get:
  # find
  - middleware.dispatcher
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.unit.create
/units/:id:
  get:
  - middleware.dispatcher
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.unit.checkOwner
  - middleware.unit.edit
/photos:
  get:
  - middleware.dispatcher
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.unit.checkOwner
  - middleware.amazon-s3
  - middleware.photo.create
/photos/:id:
  get:
  - middleware.dispatcher
/photos/:id/delete:
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.unit.checkOwner
  - middleware.photo.delete
/visits:
  post:
  - middleware.validator
  # - middleware.user.login
  # - middleware.unit.checkOwner
  - middleware.visit.create
/visits/:id:
  post:
  - middleware.validator
  # - middleware.user.login
  # - middleware.unit.checkOwner
  - middleware.visit.edit
/visits/:id/rsvp:
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.visit.rsvp
/visits/:id/unrsvp:
  post:
  - middleware.validator
  - middleware.user.login
  - middleware.visit.unrsvp
/visits/:id/delete:
  post:
  - middleware.validator
  # - middleware.user.login
  # - middleware.unit.checkOwner
  - middleware.visit.delete

...
