
controllers:
    property:
    tenant:
    unit:
    user:
    lease:
    visit:

middleware:
    bodyParser:
    contextualizer:
        environment: dev
    errorHandler:
    hb-adapter:
    logger:
        format: dev
        format-prod: '{"date":":date","msec":":response-time","addr":":remote-addr","usag":":user-agent","refr":":referrer","req":":method :url","resp":":status :res[content-length]"}'
    logwriter:
        logLevel: debug
    query:
    registry:
    router:
    tojson-errorhandler:
        statuses:
            InvalidCredentialsError: 401
            MongoError: 409

models:
    property:
    unit:
    user:
    lease:
    visit:
