
"": [
        middleware.contextualizer,
        middleware.logger,
        middleware.logwriter,
        middleware.query,
        middleware.bodyParser,
        middleware.router,
        middleware.tojson-errorhandler,
        middleware.errorHandler
    ]

"/login":
    post: [ controllers.user.login ]

"/logout":
    post: [ controllers.user.logout ]

"/register":
    post: [ controllers.user.register ]

"/user/:id":
    get:   [ controllers.user.byId ]
    patch: [ controllers.user.edit ]

"/properties":
    post: [ controllers.property.find ]
    put: [ controllers.property.create ]

"/properties/:id":
    get:    [ controllers.property.byId ]
    patch:  [ controllers.property.edit ]
    delete: [ controllers.property.remove ]

"/properties/:id/units":
    get:  [ controllers.unit.byProperty ]
    put:  [ controllers.unit.create ]

"/units":
    post: [ controllers.unit.find ]
    put:  [ controllers.unit.create ]

"/units/:id":
    get:    [ controllers.unit.byId ]
    patch:  [ controllers.unit.edit ]
    delete: [ controllers.unit.remove ]

"/units/:id/leases":
    # get:  [ controllers.lease.byUnit ]
    put:  [ controllers.lease.create ]

# "/properties/:pid/tenants/:tid":
#     get:  [ controllers.tenant.byId ]
#     patch:  [ controllers.tenant.edit ]
#     delete:  [ controllers.tenant.remove ]

# "/lease":
#     post: [ controllers.lease.find ]

"/user/:id/properties":
    get:  [ controllers.property.byUser ]

