
"": [
        middleware.contextualizer,
        middleware.logger,
        middleware.logwriter,
        middleware.query,
        middleware.bodyParser,
        middleware.router,
        middleware.tojson-errorhandler,
        middleware.errorHandler
    ]

"/login":
    post: [ controllers.user.login ]

"/logout":
    post: [ controllers.user.logout ]

"/register":
    post: [ controllers.user.register ]

"/user/:id":
    get:   [ controllers.user.byId ]
    patch: [ controllers.user.edit ]

"/properties":
    post: [ controllers.property.find ]
    put: [ controllers.property.create ]

"/properties/:id":
    get:    [ controllers.property.byId ]
    patch:  [ controllers.property.edit ]
    delete: [ controllers.property.remove ]

"/properties/:id/units":
    get:  [ controllers.unit.byProperty ]
    put:  [ controllers.unit.create ]

"/units":
    post: [ controllers.unit.find ]

"/units/:id":
    get:    [ controllers.unit.byId ]
    patch:  [ controllers.unit.edit ]
    delete: [ controllers.unit.remove ]

"/units/:id/leases":
    get:  [ controllers.lease.byUnit ]
    put:  [ controllers.lease.create ]

"/units/:id/visits":
    get:  [ controllers.lease.byUnit ]
    put:  [ controllers.visit.create ]

"/leases":
    post: [ controllers.lease.find ]

"/leases/:id":
    get:    [ controllers.lease.byId ]
    patch:  [ controllers.lease.edit ]
    delete: [ controllers.lease.remove ]

"/visits":
    post: [ controllers.visit.find ]

"/visits/:id":
    get:    [ controllers.visit.byId ]
    patch:  [ controllers.visit.edit ]
    delete: [ controllers.visit.remove ]

"/user/:id/units":
    get:  [ controllers.unit.byOwner ]

"/user/:id/leases":
    get:  [ controllers.lease.byTenant ]
